### PR TITLE
Fix gdb symbol-file argument

### LINKED ISSUE #75: Fix symbol file given to gdb
The symbol file path given to the gdb command is incorrect. We need to pass the path to the elf file in the same string as the "symbol-file" argument.

### PR DESCRIPTION
**Pull request by SamTebbs33**
Fixes the argument to symbol-file, which is passed to gdb. Closes #75

### CODE REVIEW

File: build.zig [hunk 1]
```diff
@@ -94,12 +95,12 @@ pub fn build(b: *Builder) !void {
     }
 
     const debug_step = b.step("debug", "Debug with gdb");
+    const symbol_file_arg = try std.mem.join(b.allocator, " ", [_][]const u8{ "symbol-file", elf_path });
     const debug_cmd = b.addSystemCommand([_][]const u8{
         "gdb",
         "-ex",
-        "symbol-file",
     });
```
Comment (DrDeano) [inline build.zig]: why not add the arguments here. So have:
const debug_cmd = b.addSystemCommand([_][]const u8{
    "gdb",
    "-ex",
    "symbol-file",
    elf_path ,
});

File: build.zig [hunk 2]
```diff
@@ -94,12 +95,12 @@ pub fn build(b: *Builder) !void {
...
-    debug_cmd.addArtifactArg(exec);
+    debug_cmd.addArg(symbol_file_arg);
     debug_cmd.addArgs([_][]const u8{
```
Comment (DrDeano) [inline build.zig]: Same here, just add the args to the end of the addSystemCommand

File: build.zig (hunk 1 above)
Comment (SamTebbs33) [reply build.zig]: "symbol-file" and the path have to be in the same string, so I could do
```zig
const debug_cmd = b.addSystemCommand([_][]const u8{
    "gdb",
    "-ex",
    symbol_file_arg,
});
```
instead

Comment (DrDeano) [reply build.zig]: which ever look neater/clearer
