### PR TITLE
Fix T(x) style casts

### LINKED ISSUE #110: Replace old style casts with `@as`
Zig has recently removed the `T(x)` style casts and replaced them with an `@as` builtin: https://ziglang.org/documentation/master/#as

Unnecessary casts will be removed entirely, casts in the form of `const/var x = T(y)` will be replaced with `const/var x: T = y` and anything else will be replaced with `@as`.

### PR DESCRIPTION
**Pull request by SamTebbs33**
This patch fixes the `T(x)` style casts in the codebase. Unnecessary casts were removed, those of the form `const/var x = T(y)` were replaced with `const/var x: T = y` and other were replaced with the new `@as` builtin. Closes #110

### CODE REVIEW

File: src/kernel/arch/x86/gdt.zig [hunk 1]
```diff
@@ -532,106 +532,106 @@ test "makeEntry alternating bit pattern" {
...
-    expectEqual(u32(0), tss.es);
-    expectEqual(u32(0), tss.cs);
-    expectEqual(u32(0), tss.ss);
-    expectEqual(u32(0), tss.ds);
-    expectEqual(u32(0), tss.fs);
-    expectEqual(u32(0), tss.gs);
-    expectEqual(u32(0), tss.ldtr);
-    expectEqual(u16(0), tss.trap);
-    expectEqual(u16(@sizeOf(TtsEntry)), tss.io_permissions_base_offset);
+    expectEqual(@as(u32, 0), tss.prev_tss);
```
Comment (DrDeano) [inline src/kernel/arch/x86/gdt.zig]: I think if you swap the arguments around you may not need to cast

File: src/kernel/arch/x86/paging.zig [hunk 2]
```diff
@@ -190,10 +190,10 @@ fn mapDirEntry(dir: *Directory, virt_start: usize, virt_end: usize, phys_start:
     var dir_entry = &dir.entries[entry];
     dir_entry.* |= DENTRY_PRESENT;
     dir_entry.* |= DENTRY_WRITABLE;
-    dir_entry.* &= ~u32(DENTRY_USER);
+    dir_entry.* &= ~@as(u32, DENTRY_USER);
     dir_entry.* |= DENTRY_WRITE_THROUGH;
-    dir_entry.* &= ~u32(DENTRY_CACHE_DISABLED);
-    dir_entry.* &= ~u32(DENTRY_4MB_PAGES);
+    dir_entry.* &= ~@as(u32, DENTRY_CACHE_DISABLED);
+    dir_entry.* &= ~@as(u32, DENTRY_4MB_PAGES);
```
Comment (SamTebbs33) [inline src/kernel/arch/x86/paging.zig]: I don't think these casts are necessary

File: src/kernel/arch/x86/gdt.zig (hunk 1 above)
Comment (SamTebbs33) [reply src/kernel/arch/x86/gdt.zig]: True, but then if I e.g. change 0 to 1 then it fails with "expected 0, found 1", but in reality 1 is the expected value.

Comment (DrDeano) [reply src/kernel/arch/x86/gdt.zig]: True

Comment (SamTebbs33) [reply src/kernel/arch/x86/gdt.zig]: It would be nice to not have to cast, but I reckon the expectEqual function needs to be changed for that.
